// Supabase database types
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string;
          full_name: string;
          password_hash: string;
          email_verified: boolean;
          avatar_url: string | null;
          bio: string | null;
          location: string | null;
          website_url: string | null;
          github_username: string | null;
          twitter_username: string | null;
          linkedin_url: string | null;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
          is_active: boolean;
          is_premium: boolean;
          premium_expires_at: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          username: string;
          full_name: string;
          password_hash: string;
          email_verified?: boolean;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website_url?: string | null;
          github_username?: string | null;
          twitter_username?: string | null;
          linkedin_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          is_active?: boolean;
          is_premium?: boolean;
          premium_expires_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string;
          full_name?: string;
          password_hash?: string;
          email_verified?: boolean;
          avatar_url?: string | null;
          bio?: string | null;
          location?: string | null;
          website_url?: string | null;
          github_username?: string | null;
          twitter_username?: string | null;
          linkedin_url?: string | null;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
          is_active?: boolean;
          is_premium?: boolean;
          premium_expires_at?: string | null;
        };
      };
      user_statistics: {
        Row: {
          id: string;
          user_id: string;
          total_points: number;
          current_streak: number;
          longest_streak: number;
          global_rank: number | null;
          challenges_completed: number;
          challenges_attempted: number;
          average_score: number;
          total_time_spent: number;
          practice_sessions: number;
          prompts_evaluated: number;
          prompts_saved: number;
          prompts_shared: number;
          courses_completed: number;
          lessons_completed: number;
          last_activity_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          total_points?: number;
          current_streak?: number;
          longest_streak?: number;
          global_rank?: number | null;
          challenges_completed?: number;
          challenges_attempted?: number;
          average_score?: number;
          total_time_spent?: number;
          practice_sessions?: number;
          prompts_evaluated?: number;
          prompts_saved?: number;
          prompts_shared?: number;
          courses_completed?: number;
          lessons_completed?: number;
          last_activity_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          total_points?: number;
          current_streak?: number;
          longest_streak?: number;
          global_rank?: number | null;
          challenges_completed?: number;
          challenges_attempted?: number;
          average_score?: number;
          total_time_spent?: number;
          practice_sessions?: number;
          prompts_evaluated?: number;
          prompts_saved?: number;
          prompts_shared?: number;
          courses_completed?: number;
          lessons_completed?: number;
          last_activity_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      point_transactions: {
        Row: {
          id: string;
          user_id: string;
          points: number;
          transaction_type: string;
          source_type: string;
          source_id: string | null;
          title: string;
          description: string | null;
          metadata: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          points: number;
          transaction_type: string;
          source_type: string;
          source_id?: string | null;
          title: string;
          description?: string | null;
          metadata?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          points?: number;
          transaction_type?: string;
          source_type?: string;
          source_id?: string | null;
          title?: string;
          description?: string | null;
          metadata?: string | null;
          created_at?: string;
        };
      };
      challenge_submissions: {
        Row: {
          id: string;
          user_id: string;
          challenge_id: string;
          prompt_text: string;
          submission_notes: string | null;
          overall_score: number | null;
          criteria_scores: string | null;
          ai_feedback: string | null;
          evaluation_metadata: string | null;
          attempt_number: number;
          time_spent: number | null;
          is_completed: boolean;
          points_earned: number;
          bonus_points: number;
          status: string;
          started_at: string;
          submitted_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          challenge_id: string;
          prompt_text: string;
          submission_notes?: string | null;
          overall_score?: number | null;
          criteria_scores?: string | null;
          ai_feedback?: string | null;
          evaluation_metadata?: string | null;
          attempt_number?: number;
          time_spent?: number | null;
          is_completed?: boolean;
          points_earned?: number;
          bonus_points?: number;
          status?: string;
          started_at?: string;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          challenge_id?: string;
          prompt_text?: string;
          submission_notes?: string | null;
          overall_score?: number | null;
          criteria_scores?: string | null;
          ai_feedback?: string | null;
          evaluation_metadata?: string | null;
          attempt_number?: number;
          time_spent?: number | null;
          is_completed?: boolean;
          points_earned?: number;
          bonus_points?: number;
          status?: string;
          started_at?: string;
          submitted_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      practice_sessions: {
        Row: {
          id: string;
          user_id: string;
          session_name: string | null;
          prompt_text: string;
          prompt_type: string | null;
          overall_score: number | null;
          criteria_scores: string | null;
          applicable_criteria: string[];
          ai_feedback: string | null;
          strengths: string[];
          weaknesses: string[];
          suggestions: string[];
          evaluation_model: string;
          evaluation_time: number | null;
          session_duration: number | null;
          status: string;
          points_earned: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_name?: string | null;
          prompt_text: string;
          prompt_type?: string | null;
          overall_score?: number | null;
          criteria_scores?: string | null;
          applicable_criteria?: string[];
          ai_feedback?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          suggestions?: string[];
          evaluation_model?: string;
          evaluation_time?: number | null;
          session_duration?: number | null;
          status?: string;
          points_earned?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_name?: string | null;
          prompt_text?: string;
          prompt_type?: string | null;
          overall_score?: number | null;
          criteria_scores?: string | null;
          applicable_criteria?: string[];
          ai_feedback?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          suggestions?: string[];
          evaluation_model?: string;
          evaluation_time?: number | null;
          session_duration?: number | null;
          status?: string;
          points_earned?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      saved_prompts: {
        Row: {
          id: string;
          user_id: string;
          prompt_id: string;
          prompt_title: string;
          prompt_text: string;
          prompt_description: string | null;
          category: string | null;
          tags: string[];
          difficulty: string | null;
          folder_name: string | null;
          user_notes: string | null;
          is_favorite: boolean;
          times_used: number;
          last_used_at: string | null;
          source_url: string | null;
          source_provider: string | null;
          original_author: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          prompt_id: string;
          prompt_title: string;
          prompt_text: string;
          prompt_description?: string | null;
          category?: string | null;
          tags?: string[];
          difficulty?: string | null;
          folder_name?: string | null;
          user_notes?: string | null;
          is_favorite?: boolean;
          times_used?: number;
          last_used_at?: string | null;
          source_url?: string | null;
          source_provider?: string | null;
          original_author?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          prompt_id?: string;
          prompt_title?: string;
          prompt_text?: string;
          prompt_description?: string | null;
          category?: string | null;
          tags?: string[];
          difficulty?: string | null;
          folder_name?: string | null;
          user_notes?: string | null;
          is_favorite?: boolean;
          times_used?: number;
          last_used_at?: string | null;
          source_url?: string | null;
          source_provider?: string | null;
          original_author?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_dashboard_stats: {
        Args: {
          user_id: string;
        };
        Returns: {
          total_points: number;
          completed_challenges: number;
          current_streak: number;
          global_rank: number;
          saved_prompts: number;
          average_score: number;
          practices_sessions: number;
          achievements_earned: number;
        };
      };
      get_weekly_progress: {
        Args: {
          user_id: string;
        };
        Returns: {
          day: string;
          value: number;
          points: number;
          activities: number;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}